---
- name: test stat module
  hosts: 10.23.*
  gather_facts: False


  tasks:

#    - name: test stat module on file
#      win_stat: path="C:/Windows/win.ini"
#      register: stat_file
#      notify: handler1

#    - name: check stat_file result
#      assert:
#          that:
#              - "stat_file.stat.exists"
#              - "not stat_file.stat.isdir"
#              - "stat_file.stat.size > 0"
#              - "stat_file.stat.md5"

    - name: test module raw
      raw: | 
        echo "ok" ;
        echo "good"; 
      register: test
      changed_when: True
      notify: handler1

    - debug: var=test

  handlers:
    - name: handler1
      debug: var=ansible_fqdn
      #raw: echo handler1 run 
