---

- name: ensure zabbix agent conf
  hosts: all

  vars:
    ZabbixServerNet: 10.23.220.35
    ZabbixServerCom: 10.22.117.6

  tasks:
  - name: copy zabbix package 
    win_copy:
      src: files/zabbix_autoinstall_for_win_x64.exe
      dest: c:\zabbix_autoinstall_for_win_x64.exe

  - name: install zabbix agent
    win_package:
      path: c:\zabbix_autoinstall_for_win_x64.exe
      state: install
    notify: initial zabbix service

  - name: create zabbix config file
    win_template: 
      src: templates/zabbix_agentd.win.conf.tpl
      dest: c:/zabbix/conf/zabbix_agentd.win.conf
    notify: restart zabbix agent

  handlers:
  - name: initial zabbix service
    raw: |
      C:\zabbix\bin\win64\zabbix_agentd.exe --uninstall;
      C:\zabbix\bin\win64\zabbix_agentd.exe --config c:/zabbix/conf/zabbix_agentd.win.conf --install

  - name: restart zabbix agent
    win_service: 
      name: Zabbix Agent
      state: restarted
