---
# vars file for sailfish
version: "{{sailfishversion}}"
pkgname: "sailfish-{{version}}-vpc.jar"
aft_path: "/artifactory/sailfish-release/com/datayes/sailfish"
aft_host: "{{'artifactory.datayes.net' if ansible_fqdn.lower().endswith('.net') else 'artifactory.wmcloud.com'}}"
pkgurl: "http://{{aft_host}}{{aft_path}}/{{version}}/{{pkgname}}"
