#! /bin/bash

source /etc/profile
set -e

user=pms
ulimit -SHn 65535
if [ $UID -ne 0 ];then
    echo only root can start service
    exit 1
fi

port=80
JAVA_OPTS="-Xms4096m -Xmx10240m -XX:PermSize=512M -XX:MaxPermSize=512M"

localenvs="/datayes/invest-platform/pms/etc/env-local"
if [ -f $localenvs ]; then
    source $localenvs
fi

JAVA_OPTS="$JAVA_OPTS -DallowOrigin=true"
JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true -Dhttp.port=$port"
export JAVA_OPTS

TOPDIR=/datayes/invest-platform/pms
ETCDIR=$TOPDIR/etc
WORKDIR=$TOPDIR/web

pidfile='/var/run/pms_server.pid'

case $1 in
    start)
        status=`ps -ef | grep -v grep | grep /datayes/invest-platform/pms/web | wc -l`
        if [[ $status -eq 1 ]]; then
            echo "pms_server is already running "
            exit 0
        fi
        startfile=/datayes/invest-platform/pms/web/bin/pms
        /sbin/start-stop-daemon --background --verbose --start --oknodo \
            -c $user:$user -d $TOPDIR \
            --make-pidfile --pidfile $pidfile \
            --exec /bin/bash -- -c "/usr/bin/authbind --deep $startfile > /datayes/invest-platform/pms/pmslog 2>&1"
        sleep 2
        status=`ps -ef | grep /datayes/invest-platform/pms/web | wc -l`
        if [[ $status -gt 0 ]]; then
            echo "start success"
            exit 0
        fi
        echo "start error!!"
        exit 1
        ;;

    stop)
        status=`ps -ef | grep /datayes/invest-platform/pms/web | wc -l`
        if [[ $status -eq 0 ]]; then
            echo "pms_server is already stopped"
            exit 0
        fi
        ppid=`cat $pidfile`
        for i in `ps -ef | grep /datayes/invest-platform/pms/web | awk '{print $2}'`; do
            if [[ $ppid -ne $i ]]; then
                kill $i
            fi
        done
        status=1
        count=0
        while [[ $status -eq 0 || $count -le 7 ]]; do
            sleep 2
            status=`ps -ef | grep /datayes/invest-platform/pms/web | wc -l`
            if [[ $status -eq 0 ]]; then
                echo "pms_server is stopped"
                exit 0
            fi
            count=$((count + 1))
        done
        echo "pms_server not stopped. something is wrong"
        exit 1
        ;;

    status)
        pidinfile=`cat /var/run/pms_server.pid`
        pidprocess=`ps -ef | grep /datayes/invest-platform/pms/web | awk '{print $2}' | sort | head -n 1`
        if [[ $pidinfile -eq $pidprocess ]]; then
            echo "pms_server is running, the process id is $pidinfile"
            exit 0
        fi
        echo "pms_server is not running"
        exit 1
        ;;

    *)
        echo "Usage: /etc/init.d/pms_server {start|stop|status}"
        exit 1
        ;;
esac
