---


- file:
    path: "{{pmslogbakdir}}"
    state: directory

- cron:
    name: "backup pmslog"
    job: "cp -u /datayes/invest-platform/pms/logs/pms.* {{pmslogbakdir}}/"
    minute: "10"
    hour: "0"

