---
# tasks file for pmsweb

- local_action: stat path="files/pms-{{version}}.deb"
  register: file_stat
  
- assert:
    that:
    - pmsversion is defined
    - pmsbakdir is defined
    - pmsversion is defined
    - file_stat.stat.exists


- service:
    name: pms_server
    state: stopped
  ignore_errors: yes

- apt:
    name: [authbind, unzip, openjdk-7-jdk]

- include: user.pms.yml

- file:
    path: "{{item}}"
    state: directory
  with_items:
  - "{{basedir}}"
  - "{{pmsbakdir}}"

- name: backup
  args:
    executable: /bin/bash
    chdir: "{{basedir}}"
  shell: |
    bakfile={{pmsbakdir}}/bak.$(date +%Y%m%d).pms.tar.gz
    if [ -d pms ] && [ ! -f $bakfile ]; then
      tar -czf $bakfile pms pms-*.deb /etc/init.d/pms_server --exclude *log >/dev/null 2>&1
    fi

- copy:
    dest: "/datayes/invest-platform/pms-{{version}}.deb"
    src: "../files/pms-{{version}}.deb"

- name: install
  args:
    executable: /bin/bash
    chdir: "{{basedir}}"
  shell: |
    if dpkg -l | grep pms | grep {{version}} || dpkg -i {{pkgname}} ; then
      echo dpkg install package\({{pkgname}}\) successfully
    else 
      echo dpkg install package\({{pkgname}}\) failed >&2
      exit 1
    fi

# - copy:
#     src: "../files/pms/{{application_conf}}"
#     dest: "{{basedir}}/pms/etc/application.conf"
#     owner: pms
#     group: pms
#     mode: 0644

- template:
    src: "pms.application.conf.tpl"
    dest: "{{basedir}}/pms/etc/application.conf"
    owner: pms
    group: pms
    mode: 0644

- copy:
    src: pms_server
    dest: /etc/init.d/
    mode: 0755

- service: 
    name: pms_server 
    state: started



- include: backup.pms.log.yml
  when: pmslogbakdir is defined

- include: zabbix.pms.yml

- include: backup.accountmaster.yml