---


- apt:
    name: [zabbix-agent, zabbix-sender,jq]
    update_cache: yes

- service:
    name: zabbix-agent
    state: stopped
  ignore_errors: yes

- file:
    path: "/root/scripts"
    state: directory

- name: render zabbix_agentd.conf & zabbixsender4heartbeat.sh
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - src: zabbix_agentd.conf.tpl
      dest: /etc/zabbix/zabbix_agentd.conf
    - src: zabbixsender4heartbeat.sh.tpl
      dest: /root/scripts/zabbixsender4heartbeat.sh

- cron:
    name: "heartbeat-sender"
    job: "/bin/bash -x /root/scripts/zabbixsender4heartbeat.sh > /tmp/heartbeat.log"
    minute: "*/1"

- name: restart zabbixagent
  service:
    name: zabbix-agent
    state: restarted