---
- name: test stat module
  hosts: all
  gather_facts: False


  tasks:

#    - name: test stat module on file
#      win_stat: path="C:/Windows/win.ini"
#      register: stat_file
#      notify: handler1

#    - name: check stat_file result
#      assert:
#          that:
#              - "stat_file.stat.exists"
#              - "not stat_file.stat.isdir"
#              - "stat_file.stat.size > 0"
#              - "stat_file.stat.md5"

    - name: copy zip file
      win_copy:
        src: ../files/zabbix.agent.zip 
        dest: c:\

    - name: unzip zipfile
      win_unzip:
        src: c:\zabbix.agent.zip
        dest: c:\testzabbix
     

