#! /bin/bash
set -e
export PATH="/opt/anaconda/bin:$PATH"

user=pms
if [[ $UID -ne 0 ]];then
    echo "only root can run the service"
    exit 1
fi

WORKDIR=/datayes/invest-platform/attribution
LOG_DIR=$WORKDIR/logs
pidfile='/var/run/pms_attr.pid'

case $1 in
    start)
        status=`ps -ef | grep attribution.xml | grep -v grep | grep -v pms_attr | wc -l`
        if [[ $status -gt 0 ]]; then
            echo "is already started!!!"
            exit 0
        fi
        /sbin/start-stop-daemon -c $user:$user -d $WORKDIR --start --oknodo \
            --make-pidfile --pidfile $pidfile --background --verbose  \
            --exec /bin/bash -- -c "uwsgi --master -x etc/attribution.xml"
        sleep 2
        status=`ps -ef | grep attribution.xml | grep -v grep | grep -v pms_attr | wc -l`
        if [[ $status -gt 0 ]]; then
            echo "start successfully !!!"
            exit 0
        fi
        echo "start error !!!"
        exit 1
        ;;

    stop)
        status=`ps -ef | grep attribution.xml | grep -v grep | grep -v pms_attr | wc -l`
        if [[ $status -eq 0 ]]; then
            echo "pms_attr is already stopped"
            exit 0
        fi
        ps -ef | grep attribution.xml | grep -v grep | awk '{print $2}' | xargs kill -9
        sleep 2
        status=`ps -ef | grep attribution.xml | grep -v grep | grep -v pms_attr | wc -l`
        if [[ $status -eq 0 ]]; then
            echo 'stop successfully!!!'
            exit 0
        fi
        echo "stop error !!!"
        exit 1
        ;;

    status)
        ps -ef | grep attribution.xml | grep -v grep | grep -v pms_attr
        if [ $? -eq 0 ]; then
            echo 'is running'
            exit 0
        else
            echo 'is not running'
            exit 1
        fi
        ;;

    *)
        echo "Usage: /etc/init.d/pms_attr {start|stop|status}" || true
        exit 1
esac
