---

- name: install or update attribution
  hosts: attr* pms*

  vars:
    version: "{{attrversion}}"
    aft_host: "{{'artifactory.datayes.net' if ansible_fqdn.lower().endswith('.net') else 'artifactory.wmcloud.com'}}"
    deburl: "http://{{aft_host}}/artifactory/invest-platform-release/com/datayes/attribution/{{version}}/attribution-{{version}}.deb"

  tasks:
  - name: ensure services stoped
    shell:
      bash /etc/init.d/pms_celery stop
      bash /etc/init.d/pms_attr stop
      bash /etc/init.d/zabbix-agent stop
      exit 0

  - name: install apt-packages
    apt:
      name: [mysql, unzip, rabbitmq-server]

  - file:
      dest: /usr/lib/libmysqlclient.so.18
      src: /opt/mysql/server-5.6/lib/libmysqlclient.so.18
      state: link

  - name: useradd pms
    user:
      name: pms
      password: datayes@123
      shell: /bin/bash
      createhome: yes

  - name: sudoer.d for pms
    copy:
      dest: /etc/sudoers.d/pms
      src: ../files/sudoer.pms


  - name: initialize/backup & update/create  for attribution
    args:
      executable: /bin/bash
    shell: |
      basedir="/datayes/invest-platform"
      [ -d $basedir ] || mkdir -p $basedir
      cd $basedir

      ## initialize or backup
      if [ ! -d ${basedir}/attribution ];then
        rabbitmqctl add_user pms datayes123
        rabbitmqctl add_vhost attribution
        rabbitmqctl set_permissions -p attribution pms ".*" ".*" ".*"
      else
        bakfile={{attrbakdir}}/bak.$(date +%Y%m%d).attr.tar.gz
        tar -czf $bakfile attribution* /etc/init.d/pms_attr /etc/init.d/pms_celery --exclude *log
      fi

      ## download and install package 
      basedir="/datayes/invest-platform"
      [ -d $basedir ] || mkdir -p $basedir
      cd $basedir
      rm -rf attribution-*.deb >/dev/null 2>&1
      wget {{deburl}}
      if [ ! -f attribution-{{version}}.deb ]; then
        echo download package failed >&2
        exit 1
      fi
      dpkg -l | grep attribution | grep {{version}}
      [ $? -ne 0 ] && dpkg -i attribution-{{version}}.deb
    register: script-result
  - debug: var=script-result

  - name: render template to config.cfg
    template:
      src: ../templates/config.cfg.tpl 
      dest: /datayes/invest-platform/attribution/etc/config.cfg
      owner: pms
      group: pms
      mode: 0644

  - name: copy logging.cfg to logging.cfg
    copy:
      src: ../files/logging.cfg
      dest: /datayes/invest-platform/attribution/etc/logging.cfg
      owner: pms
      group: pms
      mode: 0644


  - name: start attr service
    service: name={{ item }} state=started
    with_items:
      - pms_celery
      - pms_attr