---

- name: install or update pms
  hosts: all

  vars:
    # version: 2.6.1-35
    version: "{{pmsversion}}"
    aft_com: artifactory.wmcloud.com
    aft_net: artifactory.datayes.net
    deburl: http://{{aft_net if ansible_fqdn.lower().endswith('.net') else aft_com}}/artifactory/invest-platform-release/com/datayes/pms/{{version}}/pms-{{version}}.deb

  tasks:
  - name: state for pms
    stat: 
      path: /etc/init.d/pms_server
    register: pms_service

  - name: stop pms service
    service:
      name: pms_server
      state: stopped

  - name: install apt-packages
    apt:
      name: [mysql, authbind, unzip, openjdk-7-jdk]
    when: not pms_service.stat.exists

  - name: useradd pms
    user:
      name: pms
      password: datayes@123
      shell: /bin/bash
      createhome: yes
    when: not pms_service.stat.exists

  - name: sudoer.d for pms
    copy:
      dest: /etc/sudoers.d/pms
      src: ../files/pms
    when: not pms_service.stat.exists

  - name: authbind by port 80 for pms
    file:
      path: /etc/authbind/byport/80
      state: touch
      mode: 0755
      owner: pms
      group: pms
    when: not pms_service.stat.exists

  - name: download & install pms deb
    shell: |
      basedir="/datayes/invest-platform"
      [ -d $basedir ] || mkdir -p $basedir
      cd $basedir
      if [ -d ${basedir}/pms ];then
        bakfile=bak.$(date +%Y%m%d).pms.tar.gz
        [ -f $bakfile ] && rm $bakfile
        tar -czf ../$bakfile pms* /etc/init.d/pms_server --exclude pms/log*.log
      fi
      [ -f pms-{{version}}.deb ] || wget {{deburl}}
      dpkg -l | grep pms | grep {{version}}
      [ $? -eq 0 ] || dpkg -i pms-{{version}}.deb

  - name: render template to application.conf
    template:
      src: ../templates/application.conf.tpl 
      dest: /datayes/invest-platform/pms/etc/application.conf
      owner: pms
      group: pms
      mode: 0644

  - name: start service pms_server
    service:
      name: pms_server
      state: started