---

- name: install or update pms
  hosts: pms0*

  vars:
    version: "{{pmsversion}}"
    aft_host: "{{'artifactory.datayes.net' if ansible_fqdn.lower().endswith('.net') else 'artifactory.wmcloud.com'}}"
    deburl: "http://{{aft_host}}/artifactory/invest-platform-release/com/datayes/pms/{{version}}/pms-{{version}}.deb"

  tasks:
  - name: ensure stoped pms-service
    args:
      executable: /bin/bash
    shell: |
      if [ -f /etc/init.d/pms_server ]; then
        bash /etc/init.d/pms_server stop
      else:
        exit 0
      fi

  - apt:
      name: [authbind, unzip, openjdk-7-jdk]

  - user:
      name: pms
      password: datayes@123
      shell: /bin/bash
      createhome: yes

  - name: sudoer.d for pms
    copy:
      dest: /etc/sudoers.d/pms
      src: ../files/sudoer.pms

  - name: authbind by port 80 for pms
    file:
      path: /etc/authbind/byport/80
      state: touch
      mode: 0755
      owner: pms
      group: pms

  - name: authbind by add:port for pms
    file:
      path: /etc/authbind/byaddr/0.0.0.0:80
      state: touch
      mode: 0755
      owner: pms
      group: pms

  - name: backup & download & install pms deb
    shell: |
      basedir="/datayes/invest-platform"
      [ -d $basedir ] || mkdir -p $basedir
      cd $basedir
      ## backup
      if [ -d ${basedir}/pms ];then
        bakfile={{pmsbakdir}}/bak.$(date +%Y%m%d).pms.tar.gz
        [ -f $bakfile ] && rm $bakfile
        tar -czf $bakfile pms pms-*.deb /etc/init.d/pms_server --exclude *log
        rm -rf pms-*.deb >/dev/null 2>&1
      fi
      ## download 
      wget {{deburl}}
      if [ ! -f pms-{{version}}.deb ]; then
        echo download package\(pms-{{version}}.deb\) failed >&2
        exit 1
      fi
      ## install
      dpkg -l | grep pms | grep {{version}}
      [ $? -eq 0 ] || dpkg -i pms-{{version}}.deb
      if [ $? -ne 0 ]; then
        echo dpkg install package\(pms-{{version}}.deb\) failed >&2
        exit 1
      fi
    register: scriptResult
  - debug: var=scriptResult

  - name: render template to application.conf
    template:
      src: ../templates/application.conf.tpl 
      dest: /datayes/invest-platform/pms/etc/application.conf
      owner: pms
      group: pms
      mode: 0644

  - service: name=pms_server state=started

  