---

- name: initilized for sailfish
  hosts: pms0*

  vars:
    version: "{{sailfishversion}}"
    aft_com: artifactory.wmcloud.com
    aft_net: artifactory.datayes.net
    pkgurl: http://{{aft_net if ansible_fqdn.lower().endswith('.net') else aft_com}}/artifactory/sailfish-release/com/datayes/sailfish/{{version}}/sailfish-{{version}}.jar

  tasks:
  - name: ensure sailfish service stoped
    shell: |
      [ -f /etc/init.d/sailfish ] && bash /etc/init.d/sailfish stop
      exit 0

  - stat:
      path: /datayes/invest-platform/sailfish
    register: localSailfish

  - copy:
      src: ../files/sailfish
      dest: /datayes/invest-platform/
      mode: 0755
      owner: pms
      group: pms
      directory_mode: yes
    when: not localSailfish.stat.exists

  - copy:
      src: ../files/sailfish.service
      dest: /etc/init.d/sailfish
      mode: 0755
      owner: pms
      group: pms
      directory_mode: yes

  - name: download & create/update sailfish
    args:
      executable: /bin/bash
    shell: |
      basedir=/datayes/invest-platform
      cd $basedir
      ## backup
      if [ -d sailfish ]; then
        bakfile={{sailfishbakdir}}/bak.$(date +%Y%m%d).sailfish.tar.gz
        [ -f $bakfile ] && rm $bakfile
        tar -czf $bakfile sailfish /etc/init.d/sailfish --exclude *log
        rm sailfish
      fi
      ## download
      cd sailfish/web
      if [ ! -f sailfish-{{version}}.jar ]; then
        rm sailfish-{{version}}.jar
        wget {{pkgurl}}
      fi
      if [ ! -f $basedir/sailfish/web/sailfish-{{version}}.jar ]; then
        echo download package\(sailfish-{{version}}.jar\) failed >&2
      fi

  - service: name=sailfish state=started