---

- name: backup for pmslog
  hosts: pms0*


  tasks:

  - block:
    - file:
        path: "{{pmslogbakdir}}"
        state: directory

    - cron:
        name: "backup pmslog"
        job: "cp -u /datayes/invest-platform/pms/logs/pms.* {{pmslogbakdir}}/"
        minute: "10"
        hour: "0"

    when: pmslogbakdir is defined