---

pmsbakdir: /datayes
attrbakdir: /datayes
accountbakdir: /db

pmsversion: 2.7.1-52
attrversion: 1.4.0-6

attribution: http://localhost:9090
usermaster: http://usermaster.wmcloud-stg.com

accountmaster: 
  host: account01.gw.wmcloud.com
  port: 3306
  user: app_platform
  pass: We1come

datayesdb:
  host: real-prd03.datayes.com
  port: 3313
  user: app_pms_ro
  pass: Welcome2014_0826

trading:  
  sailfish: "false"
  enabled: "true"
  client: invest
  host : tiger01.invest.wmcloud.com
  port: 3336
  user: app.trade@datayes.com
  token: 16f98aaad4e43afcca45744a84cd50647e041f9ecb2298ec8ba1a24707b96fc8
  trader: peng.zhang@datayes.com

mdl:
  host: feeder01.cloud-data.datayes.com
  port: 9379
  token: no_token

dataapi:
  host: http://vip.newapi.wmcloud.com/v1/api
  token: no_token

web_url:
  pms: https://gw.wmcloud.com/pms_public
  f2e: https://achilles.wmcloud.com
  gw_wmcloud: https://gw.wmcloud.com
  app_wmcloud: https://app.wmcloud.com
  compliance: http://tiger01.invest.wmcloud.com:9000/compliance
