---
# vars file for account
version: "{{pmsversion}}"
pkgname: "pms-{{version}}-database.tar.gz"
aft_path: "/artifactory/invest-platform-release/com/datayes/pms"
aft_host: "{{'artifactory.datayes.net' if ansible_fqdn.lower().endswith('.net') else 'artifactory.wmcloud.com'}}"
pkgurl: "http://{{aft_host}}{{aft_path}}/{{version}}/{{pkgname}}"
